docs: better FW config
Escape-Technologies/docs pull request #141
Opened 2024-09-06 13:09 UTC by QuentinN42

2024-09-06 15:13 UTC, Gby56 requested changes

2024-09-06 15:13 UTC, Gby56 commented on docs/03-platform/03-enterprise/07-repeater.mdx
> +| `51.159.205.221` | `TCP`/`HTTPS` | `443` |
wrong ips no ? these resolve to scaleway still

2024-09-06 22:03 UTC, QuentinN42 commented on docs/03-platform/03-enterprise/07-repeater.mdx
> +| `51.159.205.221` | `TCP`/`HTTPS` | `443` |
Yes this is the tools cluster

2024-09-06 22:14 UTC, Gby56 commented on docs/03-platform/03-enterprise/07-repeater.mdx
> +| `51.159.205.221` | `TCP`/`HTTPS` | `443` |
Ok so better to keep the ips I recently updated in the docs then, these are AWS

2024-09-09 16:09 UTC, QuentinN42 commented on docs/03-platform/03-enterprise/07-repeater.mdx
> +| `51.159.205.221` | `TCP`/`HTTPS` | `443` |
Added the current IPs in the doc.

2024-09-09 16:43 UTC, Gby56 approved these changes

2024-09-09 16:43 UTC, merged