feat: repeater proxy
Escape-Technologies/docs pull request #160
Opened 2024-10-31 11:22 UTC by QuentinN42

2024-10-31 11:25 UTC, LMaxence approved these changes

2024-10-31 11:47 UTC, Gby56 requested changes

2024-10-31 11:47 UTC, Gby56 commented on docs/03-platform/03-enterprise/07-repeater.mdx
> +You so need an HTTP/2 proxy.
```suggestion
Note that as we use gRPC, the proxy must support it, which implies your proxy MUST support HTTP/2.
```

2024-11-04 08:19 UTC, LMaxence approved these changes

2024-11-04 08:29 UTC, merged